### ISSUE TITLE
To use self hosted Gitlab instance instead of gitlab.com

### ISSUE THREAD

**Issue by enajain24** [loblaw-sre/backstage-plugin-gitlab#146]
Hi Team,

May I please know if it's possible to use annotation with self-hosted Gitlab in place of gitlab.com
For instance,

```
annotations:
      gitlab.xyz.com/project-id: 'project-id' 
```

Many Thanks!

**Comment by satrox28** [comment]
Hi @enajain24 

The annotation is standard, so it will be gitlab.com but the plugin is supported for self hosted too.

**Comment by enajain24** [comment]
Thanks for your response.

So, the configuration would be like this:
```
integrations:
  gitlab:
    - host: **gitlab.domain**
      token: ${GITLAB_TOKEN}
 ```
 ```
annotations: 
  **gitlab.com**/project-id: 'project-id' #1234. This must be in quotes and can be found under Settings --> General 
      or 
  **gitlab.com**/project-slug: 'project-slug' #group_name/project_name
 ```

**Comment by satrox28** [comment]
Below are the changes to be done on app-config.yaml
```
integrations:
  gitlab:
    - host: gitlab.xyz.com
      apiBaseUrl: https://gitlab.xyz.com/api/v4 #Required for self-hosted
      token: ${GITLAB_TOKEN}

proxy:
  '/gitlabci':
    target: 'https://gitlab.xyz.com/api/v4'
    allowedMethods: ['GET']
    headers:
      PRIVATE-TOKEN: '${GITLAB_TOKEN}'

```
changes on catalog-info.yaml
```
annotations: 
  gitlab.com/project-id: 'project-id' #1234. This must be in quotes and can be found under Settings --> General 
      or 
  gitlab.com/project-slug: 'project-slug' #group_name/project_name
```
