### ISSUE TITLE
Gitlab plugin returning 404

### ISSUE THREAD

**Issue by maximiliano-b** [loblaw-sre/backstage-plugin-gitlab#155]
Hello similar to issue [114](https://github.com/loblaw-sre/backstage-plugin-gitlab/issues/114) I manage to show the GitLab tab but fail to show any data. It might be some authentication/token issue, but after running the following command in my terminal it successfully gathers the request.

`curl --request GET --header "PRIVATE-TOKEN:<Token>" https://gitlab.sample.com/api/v4/projects/123` 

I am setting it differently rather than the instructions provided, but the values show correctly when I deploy my application. I am a bit confused about how the request is sent. It is getting the following 

`https://gitlab.url.sample.com/api/proxy/gitlabci/projects/123?`

The following configuration that I have is

```
  proxy:
    'gitlabci':
      target:
        $env: GITLAB_URL
      allowedMethods: ['GET']
      headers:
        PRIVATE-TOKEN:
          $env: GITLAB_PROD_API_TOKEN
```

**Comment by maximiliano-b** [comment]
added forward slashes seem to work, both on the gitlab url and the /gitlabci
```

  proxy:
    '/gitlabci/':
      target:
        $env: GITLAB_URL
      allowedMethods: ['GET']
      headers:
        PRIVATE-TOKEN:
          $env: GITLAB_PROD_API_TOKEN
```
