### ISSUE TITLE
Getting started instructions on README.md do not call out the need to configure the integration

### ISSUE THREAD

**Issue by pragone** [loblaw-sre/backstage-plugin-gitlab#16]
After a bit of back and forth trying to get the Gitlab plugin to work with private repositories I realised from some comments in previous issues, that I should also configure an integration in the `app-config.yaml` file.

The file should look something like:
```
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}
```

and pass the token as an env variable.

The error in question whenever I tried to add an existing repository was:
```
[1] 2021-09-29T01:45:41.499Z catalog warn Unable to read url, Error: Could not get GitLab project ID for: https://gitlab.com/XXXXX/-/blob/main/catalog-info.yaml, Error: GitLab Error 'undefined', undefined type=plugin entity=location:default/generated-346f310c9eee670f6ae0fce127e6f09847afb2b1
```

Once the token config was added, the component was imported correctly
