### ISSUE TITLE
Possible to change Gitlab hostname

### ISSUE THREAD

**Issue by shackit** [loblaw-sre/backstage-plugin-gitlab#21]
Is it possible to make the catalog-info annotations to be a custom gitlab host, instead of gitlab.com? 

Example below if I remove the `gitlab.com/project-id: '908'` annotation the gitlab ci plugin does not find the component

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "netcore-demo"
  description: ""
  annotations:
    gitlab-dev.example.com/project-slug: backstage-demo/netcore-demo
    gitlab-dev.example.com/project-id: '908'
    gitlab.com/project-id: '908'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "team-a"
```

**Comment by satrox28** [comment]
Hi @shackit 

The annotation will remain the same, you just need to change the gitlab host on proxy to use other domain.

Add proxy config:
```
    target: '${GITLAB_URL}/api/v4'
    allowedMethods: ['GET']
    headers:
      PRIVATE-TOKEN: '${GITLAB_TOKEN}'

```
GitLab Token should be with of scope read_api and can be generated from this URL
