### ISSUE TITLE
How to add gitlab project id to catalog-info during Create Component

### ISSUE THREAD

**Issue by shackit** [loblaw-sre/backstage-plugin-gitlab#22]
Hi,

We have a component with yaml similar to below. We would like to during the "Create Component" process inject the gitlab project id to the catalog-info so that we enable the gitlab integration.

I cannot work out how or what to reference in order to make this work. Is it possible to get some pointers?

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id | dump }}
  description: ${{ values.description | dump }}
  annotations:    
    gitlab.com/project-id:  ${{ WHAT_TO_REFERENCE_HERE }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
```
